export const modules = [
  {
    titolo: "Suolo e biodiversità",
    descrizione: "Trascurato, abusato e consumato, il suolo è base pulsante della vita terrestre, è tessuto ricco e complesso che supporta la biodiversità e ne garantisce la resilienza. Ogni manciata di terra accoglie un mondo invisibile di microrganismi, funghi, insetti, radici che intrecciano reti vitali. Nutrimento e alleato naturale contro l’erosione, la desertificazione e i cambiamenti climatici, il suolo va conosciuto, preservato e rigenerato. La sua biodiversità sostiene la produttività agricola e aumenta la capacità della natura di autorigenerarsi. L’urbanizzazione incontrollata, con la crescita della città diffusa e infinita, e l’agricoltura convenzionale di tipo monocolturale stanno minacciando questa ricchezza, alterando equilibri secolari e riducendo la capacità del suolo di sostenere la vita. Ogni conoscenza e intervento sull’ambiente dovrebbero cominciare da qui: dal ripristino di un suolo fertile, sano e vivo, che diventa tana, rifugio e risorsa per la biodiversità terrestre e acquatica, riscoprendo un patto antico con la natura che è al tempo stesso custode e insegnante.",
    data: "dal 31 marzo al 3 maggio 2025",
    attività: [
      "Costruzione di lavagna-bacheca",
      "Costruzione di un vivaio",
      "Coperture modulari multifunzionali",
      "Workshop su allevamento galline free-range",
      "Workshop: Contesto di apprendimento con Terzo Paesaggio",
    ],
    corsi: [
      "Parchi Agricoli di Milano, Riccardo Gini, direttore Parco Nord Milano",
      "Suolo e Biodiversità in Agricoltura Rigenerativa, Matteo Mazzola, Iside Farm",
      "Ecologia e Biodiversità, Alessandra Costanzo, UniMi",
      "Biogeografia, Roberta Pennati",
      "Geopedologia, Luca Trombino, UniMi",
      "Analisi del metabolismo territoriale locale e impatti ambientali, Matteo Clementi, PoliMi dpt. DAStU",
      "Milano Porta Verde: territorio-laboratorio di ecologia, Gemma Chiaffarelli, Dottoranda UniMi",
    ],
    // download: "/moduli/dummy.pdf",
  },
  {
    titolo: "Habitat",
    descrizione: "Gli habitat sono gli spazi vitali della biodiversità, luoghi dove le specie trovano rifugio, nutrimento e opportunità di riproduzione. Ogni ecosistema, dal più vasto oceano al più piccolo stagno, rappresenta un equilibrio dinamico tra risorse ambientali e popolazioni viventi. La diversità degli habitat, dai boschi pluviali alle praterie, dalle zone umide ai deserti, è essenziale per sostenere la varietà di forme di vita sul pianeta. L’antropizzazione crescente, i cambiamenti climatici con le loro conseguenze e sinergismi, le diverse forme di inquinamento atmosferico, terrestre e dei corpi idrici stanno frammentando e degradando questi spazi, riducendo la loro capacità di supportare le comunità ecologiche. Proteggere gli habitat significa salvaguardare l’intero sistema Terra: conservare le foreste non solo come polmoni del pianeta, ma come scrigni di specie uniche; mantenere le zone umide per il loro ruolo cruciale nella depurazione delle acque e nel controllo delle alluvioni; garantire corridoi ecologici per permettere il movimento e l’adattamento delle specie. Ogni habitat è una storia di interazioni delicate, un patrimonio naturale da preservare per le generazioni presenti e per quelle che verranno.",
    data: "dal 5 maggio al 30 maggio 2025",
    attività: [
      "Modulo cucina con Terzo Paesaggio e Curaa",
      "Workshop su allevamento galline free-range",
    ],
    corsi: [
      "Geografia Fisica, Guglielmina Diolaiuti, UniMi",
      "Climatologia, Antonella Senese, UniMi",
      "Botanica, Ecologia del Paesaggio, Ilda Vagge, UniMi",
      "Clima, open data e open source tool per comprendere il clima locale, Valentina Dessì, PoliMi",
      "Analisi dei servizi ecosistemici, strumenti open source di supporto, Giulia Dataola, PoliMi dpt. DAStU",
      "Foreste e servizi forestali, Giorgio Vacchiano, UniMi",
      "Servizi Ecosistemici offerti dagli alberi: I-Tree Eco, Giorgio Vacchiano, UniMi",
    ],
    // download: "/moduli/dummy.pdf",
  },
  {
    titolo: "Agroecologia e valori estetico funzionali",
    descrizione: "L’agroecologia riconosce l’interconnessione profonda tra umanità e natura e si fonda sulla comprensione sistemica degli agroecosistemi, dove le interazioni tra piante, suolo, acqua, animali ed esseri umani sono centrali per il mantenimento dell’equilibrio ecologico. Gli agricoltori sono co-creatori di conoscenza e si evolvono attraverso l’osservazione continua, la sperimentazione, lo scambio e l’apprendimento. L’agroecologia considera le pratiche agricole come parte integrante dell’ecosistema naturale, non esterne o imposte su di esso. Questo approccio ontologico invita gli agricoltori a considerarsi non solo come produttori di alimenti, ma come custodi della terra, incaricati di mantenere l’equilibrio ecologico e la biodiversità vegetale e animale, plasmando ambienti e disegnando paesaggi che acquisiscono importanti valori funzionali-produttivi e nuovi significati culturali per le comunità umane di riferimento.",
    data: "dal 3 giugno al 22 giugno 2025",
    attività: [
      "Immagine, linguaggio e confini di senso con Arianna Vairo",
      "Meshwork con Terzo Paesaggio",
      "Estetica del Giardino con Clinica Botanica",
    ],
    corsi: [
      "Agroecologia, Stefano Bocchi, Pietro De Marinis, UniMi",
      "Agroforestazione rigenerativa in risaia, Ilda Vagge, UniMi",
      "Agroforestazione e servizi ecosistemici culturali: strumenti e metodi per la rilevazione, Alice Giulia Dal Borgo, UniMi",
      "Architettura del Paesaggio, Cristiano Del Toro, architetto paesaggista",
      "Agricoltura sintropica secondo Ernst Gotsch, Gabriel Menezes e Alessandro Di Donna",
    ],
    // download: "/moduli/dummy.pdf",
  },
  {
    titolo: "Coesione socio-territoriale e benessere psico-fisico",
    descrizione: "Il legame tra la comunità umana e il territorio è un filo invisibile ma potente, che intreccia identità culturale, relazioni sociali e salute collettiva. La coesione socio-territoriale si manifesta nella capacità di creare spazi inclusivi e resilienti, dove la qualità ambientale si traduce in qualità della vita. Un ambiente sano promuove il benessere psico-fisico delle persone: il contatto con la natura riduce lo stress, migliora le funzioni cognitive e stimola l’empatia e il senso di appartenenza. La frammentazione urbana e le disuguaglianze territoriali rischiano di spezzare tale equilibrio, escludendo comunità vulnerabili dall’accesso a risorse naturali e servizi essenziali. Integrare il verde pubblico negli spazi urbani, promuovere forme di partecipazione attiva nella gestione del territorio e valorizzare le tradizioni locali sono azioni chiave per rinsaldare il tessuto socio-ecologico. In questo contesto, il benessere individuale diventa parte di una visione collettiva, dove la salute umana e quella dell’ambiente sono indissolubilmente connesse.",
    data: "dal 23 giugno al 30 giugno",
    attività: [
      "Coprogettazione di un’azienda agricola rigenerativa con Soulfood Forestfarms",
      "L'immagine che abita l'ambiente vivente con Arianna Vairo",
      "Coprogettazione con Terzo Paesaggio",
      "Festa fine primo trimestre",
    ],
    corsi: [
      "Strategie di accesso alla terra, Paola Archetti",
      "Bright Ecologies, Caretto/Spagna",
    ],
    // download: "/moduli/dummy.pdf",
  },
  {
    titolo: "Produzione alimentare e principi attivi",
    descrizione: "La produzione alimentare moderna è chiamata a rispondere a una doppia sfida: garantire la sicurezza alimentare globale e preservare la qualità nutrizionale e funzionale degli alimenti. Oltre al loro valore energetico, molti alimenti contengono principi attivi con proprietà benefiche per la salute umana, come antiossidanti, vitamine e composti bioattivi. Questi elementi sono il risultato di processi ecologici complessi e di relazioni armoniche tra piante, suolo e clima. La standardizzazione delle coltivazioni e l’uso intensivo di agrochimici minacciano di impoverire una simile ricchezza, riducendo la diversità genetica e la qualità nutraceutica dei prodotti agricoli. È dunque necessario promuovere metodi di coltivazione rigenerativi, che valorizzino la biodiversità e migliorino la composizione biochimica degli alimenti. La ricerca scientifica, unita al sapere tradizionale, può guidare l’innovazione in questo campo, trasformando il cibo non solo in una fonte di sostentamento, ma in un alleato nella prevenzione e cura delle malattie, integrando agricoltura e salute in un ciclo virtuoso.",
    data: "dal 15 settembre al 28 settembre",
    attività: [
      "Coltivazione di ortaggi in un’azienda agricola rigenerativa con Giuseppe Bertolina, Allegricola",
      "Workshop sui materiali derivanti da scarti agricoli per il design con Alessio Battistella, PoliMi",
      "Workshop sulle filiere alimentari e il recupero degli scarti alimentari con Recup",
      "Progettazione e costruzione di tettoie multifunzionali",
    ],
    corsi: [
      "Economia circolare applicata alla produzione alimentare, Presentazione degli strumenti open source di supporto, Progetto Bioloop, PoliMi",
      "Fondamenti di apicoltura, Valeria De Carolis",
      "Il pane e la rete PAU, Davide Longoni",
    ],
    // download: "/moduli/dummy.pdf",
  },
  {
    titolo: "Materie prime. Acqua ed energia",
    descrizione: "Le materie prime, l'acqua e l'energia sono i pilastri fondamentali su cui si regge ogni attività umana e ogni ecosistema naturale. L’acqua, elemento essenziale per la vita, è al centro dei processi produttivi, agricoli e industriali, oltre che culturali, mentre le risorse energetiche modellano il ritmo dello sviluppo economico e sociale. Tuttavia, l’accesso iniquo e lo sfruttamento eccessivo di tali risorse stanno compromettendo la loro disponibilità futura. La crisi idrica e il cambiamento climatico sono segnali inequivocabili della necessità di ripensare il rapporto dell’umanità con il pianeta. Tecnologie innovative, come l’energia rinnovabile e i sistemi di gestione integrata dell’acqua, offrono soluzioni concrete per ridurre l’impatto ambientale e promuovere una transizione verso l’economia circolare. Sostenibilità non significa solo preservare queste risorse, ma anche ripristinarle: riutilizzare l’acqua attraverso sistemi avanzati di trattamento, ridurre la dipendenza dai combustibili fossili e investire in energie pulite come il solare, l’eolico e l’idroelettrico. L’adozione di un approccio olistico e sistemico è l’unica via per garantire che queste risorse essenziali continuino a sostenere la vita sulla Terra.",
    data: "dal 29 settembre al 26 ottobre",
    attività: [
      "Progettazione e realizzazione di un Rain Garden, Cristiano Del Toro",
      "Progettazione e costruzione di tettoie multifunzionali per la raccolta dell’acqua e produzione di energia",
      "Workshop sui materiali derivanti da scarti agricoli per l'architettura, Alessio Battistella, PoliMi",
    ],
    corsi: [
      "Gestione rigenerativa della risorsa idrica in azienda agricola con Lorenzo Costa",
      "Gestione sostenibile dell’acqua, introduzione ai SUDS (Sustainable Urban Draining Systems) e software open source di supporto, Progetto Bioloop, PoliMi",
      "Energie rinnovabili ed agrivoltaico, teoria e workshop, Silvia Erba e Matteo Clementi, PoliMi",
      "Analisi del ciclo di vita delle risorse naturali, Giovanni Dotelli, PoliMi dpt. CMIC",
    ],
    // download: "/moduli/dummy.pdf",
  },
  {
    titolo: "Regolazione climatica e rischio idrogeologico",
    descrizione: "La regolazione climatica e la mitigazione del rischio idrogeologico rappresentano due facce di uno stesso equilibrio, quello tra i sistemi naturali e le attività umane. Gli ecosistemi terrestri e acquatici agiscono come stabilizzatori del clima, assorbendo anidride carbonica, regolando la temperatura e trattenendo l'umidità. Allo stesso tempo, elementi come le foreste, le zone umide e i suoli sani offrono una protezione naturale contro frane, alluvioni e siccità, attenuando l’impatto degli eventi estremi. La deforestazione, l’urbanizzazione selvaggia e l’alterazione dei corsi d’acqua stanno indebolendo queste difese naturali, rendendo i territori più fragili e aumentandone la vulnerabilità. La pianificazione sostenibile deve dunque integrare la conoscenza scientifica dei processi climatici e idrogeologici, promuovendo grandi e piccole soluzioni basate sulla natura: riforestazione, rinaturalizzazione dei bacini fluviali e pratiche agricole che migliorano la capacità del suolo di trattenere l’acqua quali l’agroforestazione. Ridurre i rischi idrogeologici significa anche affrontare il cambiamento climatico con un approccio preventivo, investendo in resilienza ambientale e comunitaria per tutelare sia gli ecosistemi sia le società che ne dipendono.",
    data: "dal 27 ottobre al 9 novembre",
    attività: [
      "Workshop di ingegneria naturalistica per la prevenzione del dissesto idrogeologico",
      "Workshop: Uso della motosega",
      "Coltivazioni arboree",
    ],
    corsi: [
      "Soluzioni basate sulla natura per la resilienza climatica (strategie di adattamento) con Valentina Dessì, PoliMi dpt. DAStU",
      "Immagini Satellitari e indici di vegetazione",
      "Mercato VCM e crediti di carbonio",
    ],
    // download: "/moduli/dummy.pdf",
  },
  {
    titolo: "Depurazione aria, acqua e suolo",
    descrizione: "La qualità di aria, acqua e suolo è un indicatore cruciale della salute dell’ambiente e, di riflesso, della salute umana. Questi tre elementi, intrecciati in un ciclo continuo, rappresentano il substrato su cui si costruiscono gli ecosistemi. La depurazione naturale svolta dagli ecosistemi è un servizio essenziale: foreste e oceani assorbono CO₂ e rilasciano ossigeno, zone umide filtrano inquinanti dall'acqua e i microrganismi presenti nel suolo degradano sostanze tossiche. Le pressioni antropiche, come le emissioni industriali, l’uso di pesticidi e lo smaltimento improprio dei rifiuti, stanno sovraccaricando questi sistemi naturali, compromettendone la capacità depurativa. È dunque importante investire in tecnologie sostenibili che imitino i processi naturali, come fitodepurazione, biofiltri e sistemi di trattamento avanzati per le acque reflue. Al contempo, politiche di riduzione delle emissioni inquinanti e interventi di bonifica ambientale possono ristabilire la funzionalità degli ecosistemi compromessi. Promuovere un’azione integrata per depurare aria, acqua e suolo significa garantire il benessere della vita sulla Terra e preservare i cicli vitali che sostengono il pianeta.",
    data: "dal 11 novembre al 30 novembre",
    attività: [
      "Progettazione di un sistema fitorimediante",
      "Depurazione e raccolta acqua piovana",
      "Potatura di alberi da frutto e forestali",
      "Messa a dimora di un sistema agroforestale",
      "Restituzioni e festa finale!",
    ],
    corsi: [
      "Esperienze di Fitorimedio in Italia, Massimo Fagnano",
      "Sensoristica DIY per l’analisi di aria suolo e acqua con Paolo Bonelli",
    ],
    // download: "/moduli/dummy.pdf",
  },
];