export const modules = [
  {
    titolo: "Suolo e biodiversità",
    descrizione: " Studiare, osservare, comunicare. Il suolo è una piazza della vita terrestre e l’elemento fisico e biotico a complessità più elevata e diversificata. Il suolo è uno dei sistemi più fragili e compromessi della biosfera, ma rappresenta anche una delle più straordinarie opportunità di rigenerazione. In questo modulo verranno affrontati i concetti fondamentali dell’agroecologia, della biodiversità, della fisica e chimica del suolo e delle pratiche agronomiche rigenerative. Il modulo include esercitazioni sul campo e visite a esperienze agricole di rigenerazione del paesaggio. Particolare attenzione sarà dedicata ai servizi ecosistemici, ai cicli della sostanza organica e ai metodi di monitoraggio della fertilità. Interverranno agronomi, ricercatori, docenti universitari, tecnici del verde urbano e forestale, nonché esperti di pedologia e microbiologia.",
    data: "dal 7 marzo al 3 maggio 2026",
    corsi: [
      "Paolo Ajmone Marsan, Ricercatore CREA, Università Cattolica di Milano",
      "Andrea Bucci, Agronomo, Associazione Rigenerazione Urbana Milano",
      "Altri docenti in via di definizione",
    ],
	prezzo: 500,
    download: "https://calendar.google.com/calendar/embed?src=c_faf29b58128db524f1bcb906373867e60e457030e1f864f1d9157afee43d3e49%40group.calendar.google.com&ctz=Europe%2FRome",
  },
  {
    titolo: "Habitat",
    descrizione: " Gli habitat sono ecosistemi nei quali diverse comunità biologiche interagiscono tra loro e con l’ambiente fisico. In questo modulo verranno esplorati gli habitat naturali e seminaturali, urbani e periurbani, con un’attenzione particolare alle dinamiche ecologiche, al restauro e alla gestione sostenibile del paesaggio. Saranno affrontati i principi della progettazione ecologica, della riforestazione, dell’agricoltura multifunzionale e della tutela degli spazi naturali. Le lezioni alterneranno contenuti teorici a visite sul campo e attività pratiche in contesti reali.",
    data: "dal 10 maggio al 28 giugno 2026",
    corsi: [
      "Giovanni Sala, Architetto del paesaggio, Politecnico di Milano",
      "Maria Lorusso, Ecologa, Università Statale di Milano",
      "altri docenti e professionisti ospiti",
    ],
	prezzo: 600,
    download: "https://calendar.google.com/calendar/embed?src=c_faf29b58128db524f1bcb906373867e60e457030e1f864f1d9157afee43d3e49%40group.calendar.google.com&ctz=Europe%2FRome",
  },
  {
    titolo: "Agroecologia e valori estetico funzionali",
    descrizione: " Il modulo si concentra sull’integrazione tra agroecologia, architettura e paesaggio. L’obiettivo è sviluppare competenze capaci di coniugare la funzionalità agronomica con la bellezza estetica dei paesaggi rurali e urbani. Saranno affrontati i temi del disegno del paesaggio, dell’arte ambientale, delle relazioni tra uomo e natura e del ruolo del paesaggio come bene comune.",
    data: "dal 19 settembre al 27 ottobre 2026",
    corsi: [
      "Andrea Branzi, Politecnico di Milano",
      "Matteo Mariani, Agronomo e progettista paesaggista",
      "ospiti esterni",
    ],
	prezzo: 500,
    download: "https://calendar.google.com/calendar/embed?src=c_faf29b58128db524f1bcb906373867e60e457030e1f864f1d9157afee43d3e49%40group.calendar.google.com&ctz=Europe%2FRome",
  },
  {
    titolo: "Coesione socio-territoriale e benessere psico-fisico",
    descrizione: " Il modulo affronta il rapporto tra paesaggio, comunità e salute. Verranno analizzati gli aspetti sociali, culturali ed economici connessi alla gestione degli spazi agroecologici. Un focus sarà dedicato alla capacità dei paesaggi rigenerati di favorire la coesione sociale, il benessere psicologico e la qualità della vita urbana e rurale. Saranno coinvolti sociologi, urbanisti, psicologi ambientali e progettisti territoriali.",
    data: "dal 28 giugno al 26 luglio 2026",
    corsi: [
      "Strategie di accesso alla terra, Paola Archetti",
      "Bright Ecologies, Caretto/Spagna",
      "Il benessere psicologico tra identità individuale e comunità: il ruolo degli ambienti naturali e agricoli, Nicola Rainisio, UniMi",
    ],
	prezzo: 300,
    download: "https://calendar.google.com/calendar/embed?src=c_faf29b58128db524f1bcb906373867e60e457030e1f864f1d9157afee43d3e49%40group.calendar.google.com&ctz=Europe%2FRome",
  },
  {
    titolo: "Produzione alimentare e principi attivi",
    descrizione: " Il modulo approfondisce il tema della produzione alimentare con un approccio agroecologico. Si analizzeranno le colture vegetali, le produzioni locali e il ruolo dei principi attivi contenuti negli alimenti. Le lezioni includeranno esperienze in campo, incontri con produttori e laboratori di trasformazione alimentare.",
    data: "dal 6 settembre al 25 ottobre 2026",
    corsi: [
      "Economia circolare applicata alla produzione alimentare, Presentazione degli strumenti open source di supporto, PoliMi dpt. DAStU",
      "Fondamenti di apicoltura, Valeria De Carolis",
      "Il pane e la rete PAU, Davide Longoni",
    ],
	prezzo: 400,
    download: "https://calendar.google.com/calendar/embed?src=c_faf29b58128db524f1bcb906373867e60e457030e1f864f1d9157afee43d3e49%40group.calendar.google.com&ctz=Europe%2FRome",
  },
  {
    titolo: "Materie prime. Acqua ed energia",
    descrizione: "Il modulo affronta la gestione delle risorse naturali fondamentali: acqua, energia e materie prime. Saranno trattati i principi di sostenibilità energetica, le pratiche di conservazione idrica, l’uso delle energie rinnovabili e la valorizzazione delle materie locali. Un’attenzione particolare sarà dedicata al ruolo delle comunità locali e alle politiche di gestione sostenibile.",
    data: "dal 25 ottobre al 6 dicembre 2026",
    corsi: [
      "Simone Lorenzi, Ingegnere ambientale, Politecnico di Milano",
      "Lucia Colombo, Biologa ambientale",
      "ospiti esterni",
    ],
	prezzo: 700,
    download: "https://calendar.google.com/calendar/embed?src=c_faf29b58128db524f1bcb906373867e60e457030e1f864f1d9157afee43d3e49%40group.calendar.google.com&ctz=Europe%2FRome",
  },
  {
    titolo: "Regolazione climatica e rischio idrogeologico",
    descrizione: " La regolazione climatica e la gestione del rischio idrogeologico sono aspetti centrali della resilienza territoriale. Il modulo affronterà i cambiamenti climatici, la gestione delle acque e i fenomeni di dissesto idrogeologico, fornendo strumenti tecnici e pratici per la mitigazione e l’adattamento. Saranno coinvolti esperti di climatologia, ingegneria idraulica e gestione forestale.",
    data: "dal 27 ottobre al 30 novembre 2026",
	prezzo: 300,
    corsi: [
      "Marco Galli, Ingegnere idraulico, Politecnico di Torino",
      "Chiara Neri, Climatologa, CNR",
      "ospiti esterni",
    ],
    download: "https://calendar.google.com/calendar/embed?src=c_faf29b58128db524f1bcb906373867e60e457030e1f864f1d9157afee43d3e49%40group.calendar.google.com&ctz=Europe%2FRome",
  },
  {
    titolo: "Depurazione aria, acqua e suolo",
    descrizione: " Il modulo analizza i processi naturali e tecnologici di depurazione dell’aria, dell’acqua e del suolo. Saranno illustrate tecniche di fitodepurazione, sistemi di filtraggio e buone pratiche di riduzione dell’inquinamento. Particolare rilievo sarà dato alle soluzioni basate sulla natura (Nature Based Solutions).",
    data: "dal 16 novembre al 20 dicembre 2026",
    corsi: [
      "Alessandra Fumagalli, Ricercatrice, Università Bicocca di Milano",
      "Michele Ruggiero, Ingegnere ambientale",
      "ospiti esterni",
    ],
    download: "https://calendar.google.com/calendar/embed?src=c_faf29b58128db524f1bcb906373867e60e457030e1f864f1d9157afee43d3e49%40group.calendar.google.com&ctz=Europe%2FRome",
  },
];